namespace Validly.Details;

/// <summary>
/// Details of validation result
/// </summary>
public class ValidationResultDetails
{
	/// <summary>
	/// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
	/// dereferenced, it provide human-readable documentation for the problem type
	/// (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be
	/// "about:blank".
	/// </summary>
	public string Type => "https://tools.ietf.org/html/rfc9110#section-15.5.1";

	/// <summary>
	/// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
	/// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
	/// see[RFC7231], Section 3.4).
	/// </summary>
	public string Title => "One or more validation errors occurred.";

	/// <summary>
	/// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
	/// </summary>
	public int? Status => 400;

	/// <summary>
	/// Details of validation errors
	/// </summary>
	public required IReadOnlyList<ValidationErrorDetail> Errors { get; init; }
}
